version: 2
jobs:
  build:
    # working_directory: ~/demo-app
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: demo-app-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: demo-app-{{ checksum "pom.xml" }}
      - run: mvn package
      - store_artifacts:
          path: target/demo-0.0.1-SNAPSHOT.jar #需要上传的文件路径
      - run:
          name: Show output folder
          command: |
            pwd;
            ls -al;
  deploy:
    machine:
      enabled: true
    working_directory: ~/demo-app
    steps:
      - run:
          name: Fix ssh Could not resolve hostname
          command: |
            ssh-keyscan 47.101.145.120 >> ~/.ssh/known_hosts
      - add_ssh_keys:
          fingerprints:
            - "73:c6:8d:5d:5b:fa:25:75:a2:e0:6f:23:37:16:41:c6"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build