version: 2
jobs:
  build:
    working_directory: ~/demo-app
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: demo-app-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: demo-app-{{ checksum "pom.xml" }}
      - run: mvn package
      - store_artifacts:
          path: target/demo-0.0.1-SNAPSHOT.jar #需要上传的文件路径
      - run:
          name: Prepare deployment package
          command: |
            mkdir build
            cp target/demo-0.0.1-SNAPSHOT.jar build
            cp .circleci/deploy.sh build
      - persist_to_workspace:
          root: .
          paths:
            - build
  deploy:
    machine:
      enabled: true
    working_directory: ~/demo-app
    steps:
      - run:
          name: Fix ssh Could not resolve hostname
          command: |
            ssh-keyscan 47.101.145.120 >> ~/.ssh/known_hosts
      - add_ssh_keys:
          fingerprints:
            - "73:c6:8d:5d:5b:fa:25:75:a2:e0:6f:23:37:16:41:c6"
      - attach_workspace:
          at: build
      - run:
          name: Upload artifacts to server
          command: |
            ls -al
            ls -al build/build
            # ls -al .circleci
            # scp .circleci/deploy.sh root@47.101.145.120:~
            # scp target/demo-0.0.1-SNAPSHOT.jar root@47.101.145.120:~
            # ssh root@47.101.145.120 'chmod 777 deploy.sh;ls -al;./deploy.sh;rm deploy.sh'

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build # Only run deploy job once the build job has completed
          filters:
            branches:
              only: master # Only deploy when the commit is on the Master branch